In [24]:
import cv2
import numpy as np

In [25]:
# Load the data, converters convert the letter to a number
data= np.loadtxt('alphabets.data', dtype= 'float32', delimiter = ',',
                    converters= {0: lambda ch: ord(ch)-ord('A')})

In [26]:
# split the data to two, 10000 each for train and test
train, test = np.vsplit(data,2)
print(train)

[[19.  2.  8. ...  8.  0.  8.]
 [ 8.  5. 12. ...  8.  4. 10.]
 [ 3.  4. 11. ...  7.  3.  9.]
 ...
 [ 9.  5. 11. ...  7.  0.  7.]
 [22.  4.  9. ... 11.  3.  9.]
 [16.  5. 10. ...  8.  4.  8.]]


In [27]:
# split trainData and testData to features and responses
train_labels, train = np.hsplit(train,[1])
test_labels, test = np.hsplit(test,[1])
print(train)
print('\n_____\n')
print(train_labels)

[[ 2.  8.  3. ...  8.  0.  8.]
 [ 5. 12.  3. ...  8.  4. 10.]
 [ 4. 11.  6. ...  7.  3.  9.]
 ...
 [ 5. 11.  7. ...  7.  0.  7.]
 [ 4.  9.  6. ... 11.  3.  9.]
 [ 5. 10.  7. ...  8.  4.  8.]]

_____

[[19.]
 [ 8.]
 [ 3.]
 ...
 [ 9.]
 [22.]
 [16.]]


## TRAINING

In [28]:
# Initiate kNN, train the data, then test it with test data for k=1
knn = cv2.ml.KNearest_create()
knn.train(train,cv2.ml.ROW_SAMPLE,train_labels)
#TEST WITH knn.findNearest(2DpArr , k=5)

True

## TESTING ACCURACY

In [30]:
ret, result, neighbours, dist = knn.findNearest(test, k=5)
correct = np.count_nonzero(result == labels)
accuracy = correct*100.0/10000
print (accuracy)

93.06


## SAVING AND LOADING

In [31]:
np.savez('alphabets_data.npz',train=train, train_labels=train_labels)

In [32]:
with np.load('alphabets_data.npz') as data:
    print (data.files)
    train = data['train']
    train_labels = data['train_labels']

['train', 'train_labels']


In [34]:
print (train)
print('\n_____\n')
print(train_labels)

[[ 2.  8.  3. ...  8.  0.  8.]
 [ 5. 12.  3. ...  8.  4. 10.]
 [ 4. 11.  6. ...  7.  3.  9.]
 ...
 [ 5. 11.  7. ...  7.  0.  7.]
 [ 4.  9.  6. ... 11.  3.  9.]
 [ 5. 10.  7. ...  8.  4.  8.]]

_____

[[19.]
 [ 8.]
 [ 3.]
 ...
 [ 9.]
 [22.]
 [16.]]


In [ ]:
###END###