In [136]:
import numpy as np
import cv2

In [137]:
#read file
img = cv2.imread('digits.png')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [138]:
# Now we split the image to 5000 cells, each 20x20 size
cells = [np.hsplit(row,100) for row in np.vsplit(gray,50)]

In [139]:
# Make it into a Numpy array. It size will be (50,100,20,20)
x = np.array(cells)

In [148]:
# Now we prepare train_data and test_data.
train = x[:,:50].reshape(-1,400).astype(np.float32) # Size = (2500,400)
test = x[:,50:100].reshape(-1,400).astype(np.float32) # Size = (2500,400)
print(train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [149]:
# Create labels for train and test data
k = np.arange(10)
train_labels = np.repeat(k,250)[:,np.newaxis]
test_labels = train_labels.copy()
print(train)
print('\n_____\n')
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

_____

[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]


## TRAINING

In [142]:
# Initiate kNN, train the data, then test it with test data for k=1
knn = cv2.ml.KNearest_create()
knn.train(train,cv2.ml.ROW_SAMPLE,train_labels)
#TEST WITH knn.findNearest(2DpArr , k=5)

True

## TESTING ACCURACY

In [143]:
ret,result,neighbours,dist = knn.findNearest(test,k=5)
matches = result==test_labels
correct = np.count_nonzero(matches)
accuracy = correct*100.0/result.size
print (accuracy)

91.76


## CUSTOM TESTING

In [153]:
##testing element 1352 out of 2500 test data[find nearest only accepts a 2D input of type np.array]
input = np.array([test[1922]])
ret,result,neighbours,dist = knn.findNearest(input,k=5)
result

array([[7.]], dtype=float32)

## SAVING AND LOADING MODEL

In [145]:
np.savez('digits_data.npz',train=train, train_labels=train_labels)

In [146]:
with np.load('digits_data.npz') as data:
    print (data.files)
    train = data['train']
    train_labels = data['train_labels']

['train', 'train_labels']


In [147]:
print(train)
print('\n_____\n')
print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

_____

[[0]
 [0]
 [0]
 ...
 [9]
 [9]
 [9]]


In [ ]:
###END###